<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\CustomerUserService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnusualSuspect.DataLayer\UnusualSuspect.DataLayer.csproj" />
    <ProjectReference Include="..\UnusualSuspect.Entities\UnusualSuspect.Entities.csproj" />
    <ProjectReference Include="..\UnusualSuspect.ViewModels\UnusualSuspect.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Dapper" Version="2.1.89" />
    <PackageReference Include="ElmahCore" Version="2.1.2" />
    <PackageReference Include="Hangfire" Version="1.8.25" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="Aspose.Cells">
		  <HintPath>..\Dll\Aspose\Aspose.Cells.dll</HintPath>
		</Reference>
		<Reference Include="Aspose.Cells.GridWeb">
		  <HintPath>..\Dll\Aspose\Aspose.Cells.GridWeb.dll</HintPath>
		</Reference>
		<Reference Include="Kendo.Mvc">
			<HintPath>..\Dll\Kendo.Mvc.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
