<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ElmahCore" Version="2.1.2" />
    <PackageReference Include="ElmahCore.Sql" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="NetCore.AutoRegisterDi" Version="2.2.1" />
    <PackageReference Include="Quartz" Version="4.4.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="4.4.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnusualSuspect.Common\UnusualSuspect.Common.csproj" />
    <ProjectReference Include="..\UnusualSuspect.Services\UnusualSuspect.Services.csproj" />
    <ProjectReference Include="..\UnusualSuspect.ViewModels\UnusualSuspect.ViewModels.csproj" />
  </ItemGroup>

</Project>
