// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnusualSuspect.DataLayer.Context;

#nullable disable

namespace UnusualSuspect.DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231022093945_anyChanges")]
    partial class anyChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.CharacterCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CharacterCard");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedTime")
                        .HasColumnType("datetime2");

                    b.Property<short>("GameTypeId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.GameType", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("NumberOfPlayers")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("GameType");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.JoinedPreGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOwnerOfPreGroup")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreGameGroupId")
                        .HasColumnType("int");

                    b.Property<short>("ReadyToGameStatusId")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreGameGroupId");

                    b.HasIndex("ReadyToGameStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("JoinedPreGame");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.Participate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterCardId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short>("OrderOfParticipation")
                        .HasColumnType("smallint");

                    b.Property<int>("RoleCardId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterCardId");

                    b.HasIndex("GameId");

                    b.HasIndex("RoleCardId");

                    b.HasIndex("UserId");

                    b.ToTable("Participate");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.PreGameGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("CalulatedJoinedUsers")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<short>("GameTypeId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ReadyToGameTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.ToTable("PreGameGroup");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.Question", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.QuestionGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<short>("QuestionId")
                        .HasColumnType("smallint");

                    b.Property<short>("Turn")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionGame");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.ReadyToGameStatus", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReadyToGameStatus");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.RoleCard", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleCard");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.RoleCardGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMurderer")
                        .HasColumnType("bit");

                    b.Property<short?>("RemovedTurn")
                        .HasColumnType("smallint");

                    b.Property<int>("RoleCardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("RoleCardId");

                    b.ToTable("RoleCardGame");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AppVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeForResetPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExpireToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("FireBaseToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Lastlogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MobileToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatchImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumberValidationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SendCodeDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("SoftSectionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("SoftSectionId");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.AMAreaName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AMAreaName");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.AMController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AMAreaNameId")
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FarsiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoftSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AMAreaNameId");

                    b.HasIndex("SoftSectionId");

                    b.ToTable("AMController");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.ActionForRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmActionId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmActionId");

                    b.HasIndex("RoleId");

                    b.ToTable("ActionForRole");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.ActionForSoftwareRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmActionId")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmActionId");

                    b.HasIndex("SoftwareRoleId");

                    b.ToTable("ActionForSoftwareRole");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.ActionForUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmActionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmActionId");

                    b.HasIndex("UserId");

                    b.ToTable("ActionForUser");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.AmAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AMControllerId")
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FarsiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoftSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AMControllerId");

                    b.HasIndex("SoftSectionId");

                    b.ToTable("AmAction");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.CategorySoftwareRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategorySoftwareRole");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.SoftSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoftSection");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaName = "AdminPanel",
                            TypeName = "پنل مدیریت"
                        });
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.SoftwarerRoleForUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareRoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("SoftwarerRoleForUser");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.AdminNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminNotification");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.AdminPanleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AdminPanleUser");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.CustomMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AMActionId")
                        .HasColumnType("int");

                    b.Property<int?>("AMNotifActionId")
                        .HasColumnType("int");

                    b.Property<string>("ActionAndControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontAweSomeIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotifName")
                        .HasColumnType("int");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PatchIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("SoftSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AMActionId");

                    b.HasIndex("AMNotifActionId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SoftSectionId");

                    b.ToTable("CustomMenu");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("KeyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.HomeMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("HomeMenu");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.LogObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NextValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectTypeId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PerValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("LogObject");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.ObjectType", b =>
                {
                    b.Property<string>("ObjectKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjectKey");

                    b.ToTable("ObjectType");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.SmsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeAddedToQueue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeSent")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Identifier")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadForSending")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSend")
                        .HasColumnType("bit");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<short>("SendAttemptCount")
                        .HasColumnType("smallint");

                    b.Property<string>("SendingError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("SmsSendingStatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("SmsSendingStatusId");

                    b.ToTable("SmsLog");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.SmsSendingStatus", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SmsSendingStatus");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.SoftSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BussinessTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactUsEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactUsMobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactUsPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentContactUsPage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMSNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmallTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoftSetting");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.Game", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.GameModels.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.JoinedPreGame", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.GameModels.PreGameGroup", "PreGameGroup")
                        .WithMany()
                        .HasForeignKey("PreGameGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.GameModels.ReadyToGameStatus", "ReadyToGameStatus")
                        .WithMany()
                        .HasForeignKey("ReadyToGameStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PreGameGroup");

                    b.Navigation("ReadyToGameStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.Participate", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.GameModels.CharacterCard", "CharacterCard")
                        .WithMany()
                        .HasForeignKey("CharacterCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.GameModels.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.GameModels.RoleCard", "RoleCard")
                        .WithMany()
                        .HasForeignKey("RoleCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("CharacterCard");

                    b.Navigation("Game");

                    b.Navigation("RoleCard");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.PreGameGroup", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.GameModels.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.QuestionGame", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.GameModels.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.GameModels.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.GameModels.RoleCardGame", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.GameModels.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.GameModels.RoleCard", "RoleCard")
                        .WithMany()
                        .HasForeignKey("RoleCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("RoleCard");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Identity.Role", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.SoftSection", "SoftSection")
                        .WithMany()
                        .HasForeignKey("SoftSectionId");

                    b.Navigation("SoftSection");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.AMController", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.AMAreaName", "AMAreaName")
                        .WithMany("AMControllers")
                        .HasForeignKey("AMAreaNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.SoftSection", "SoftSection")
                        .WithMany()
                        .HasForeignKey("SoftSectionId");

                    b.Navigation("AMAreaName");

                    b.Navigation("SoftSection");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.ActionForRole", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.AmAction", "AmAction")
                        .WithMany("ActionForRoles")
                        .HasForeignKey("AmActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.Identity.Role", null)
                        .WithMany("ActionForRole")
                        .HasForeignKey("RoleId");

                    b.Navigation("AmAction");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.ActionForSoftwareRole", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.AmAction", "AmAction")
                        .WithMany("ActionForSoftwareRoles")
                        .HasForeignKey("AmActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("SoftwareRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AmAction");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.ActionForUser", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.AmAction", "AmAction")
                        .WithMany("ActionForUsers")
                        .HasForeignKey("AmActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("ActionForUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AmAction");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.AmAction", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.AMController", "AMController")
                        .WithMany("AmActions")
                        .HasForeignKey("AMControllerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.SoftSection", "SoftSection")
                        .WithMany()
                        .HasForeignKey("SoftSectionId");

                    b.Navigation("AMController");

                    b.Navigation("SoftSection");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.SoftwarerRoleForUser", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.AdminPanleUser", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.CustomMenu", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.AmAction", "AmAction")
                        .WithMany()
                        .HasForeignKey("AMActionId");

                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.AmAction", "AmNotifAction")
                        .WithMany()
                        .HasForeignKey("AMNotifActionId");

                    b.HasOne("UnusualSuspect.Entities.Models.CustomMenu", "ParentCustomMenu")
                        .WithMany("ChildeCustomeMenus")
                        .HasForeignKey("ParentId");

                    b.HasOne("UnusualSuspect.Entities.JcoSecurity.SoftSection", "SoftSection")
                        .WithMany()
                        .HasForeignKey("SoftSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AmAction");

                    b.Navigation("AmNotifAction");

                    b.Navigation("ParentCustomMenu");

                    b.Navigation("SoftSection");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.LogObject", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Models.ObjectType", "ObjectType")
                        .WithMany()
                        .HasForeignKey("ObjectTypeId");

                    b.HasOne("UnusualSuspect.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("ObjectType");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.SmsLog", b =>
                {
                    b.HasOne("UnusualSuspect.Entities.Models.SmsSendingStatus", "SmsSendingStatus")
                        .WithMany()
                        .HasForeignKey("SmsSendingStatusId");

                    b.Navigation("SmsSendingStatus");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("ActionForUsers");

                    b.Navigation("Claims");

                    b.Navigation("Logins");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Identity.Role", b =>
                {
                    b.Navigation("ActionForRole");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.AMAreaName", b =>
                {
                    b.Navigation("AMControllers");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.AMController", b =>
                {
                    b.Navigation("AmActions");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.JcoSecurity.AmAction", b =>
                {
                    b.Navigation("ActionForRoles");

                    b.Navigation("ActionForSoftwareRoles");

                    b.Navigation("ActionForUsers");
                });

            modelBuilder.Entity("UnusualSuspect.Entities.Models.CustomMenu", b =>
                {
                    b.Navigation("ChildeCustomeMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
