<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	<Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnusualSuspect.Entities\UnusualSuspect.Entities.csproj" />
    <ProjectReference Include="..\UnusualSuspect.Services\UnusualSuspect.Services.csproj" />
    <ProjectReference Include="..\UnusualSuspect.ViewModels\UnusualSuspect.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Kendo.Mvc">
      <HintPath>..\Dll\Kendo.Mvc.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
